Updating auto-installer

diff --git a/init/install-organl-zsh-theme b/init/install-organl-zsh-theme
--- a/init/install-organl-zsh-theme
+++ b/init/install-organl-zsh-theme
@@ -1,8 +1,16 @@
 #!/bin/zsh
 
+ROOT=$(echo $0:A | sed -E 's/\/init\/.*//')
+NAME=$(basename ${0})
+INIT=${ROOT}/init
+
+if [ ! -d ~/.oh-my-zsh ]; then
+  ${INIT}/install-oh-my-zsh || { echo "Unable to bootstrap oh-my-zsh!" && exit -1 }
+fi
+
 if [ ! -d ~/.oh-my-zsh/custom/.git ]; then
-    cd ~/.oh-my-zsh
-    rm -rf ~/.oh-my-zsh/custom
-    git clone git@github.com:organl/oh-my-zsh-organl.git custom
+    { cd ~/.oh-my-zsh && \
+      rm -rf ~/.oh-my-zsh/custom && \
+      git clone git@github.com:organl/oh-my-zsh-organl.git custom } || { echo "Unable to bootstrap oh-my-zsh OrganL theme!" && exit -1}
 fi
 
