Improved auto-installation scripts

diff --git a/init/install-oh-my-zsh b/init/install-oh-my-zsh
--- a/init/install-oh-my-zsh
+++ b/init/install-oh-my-zsh
@@ -1,3 +1,11 @@
 #!/bin/zsh
 
-[ ! -d ~/.oh-my-zsh ] && git clone git@github.com:ohmyzsh/ohmyzsh.git ~/.oh-my-zsh
+if [ ! -d ~/.oh-my-zsh ]; then
+  echo "Cloning ohmyzsh (RW): ~/.oh-my-zsh"
+  git clone git@github.com:ohmyzsh/ohmyzsh.git ~/.oh-my-zsh
+  then [ $? -eq 0 ];
+    echo "Clone of failed, trying fallback..."
+    echo "Cloning ohmyzsh (RO): ~/.oh-my-zsh"
+    git clone https://github.com/ohmyzsh/ohmyzsh.git ~/.oh-my-zsh
+  fi 
+fi
diff --git a/init/install-organl-zsh-theme b/init/install-organl-zsh-theme
--- a/init/install-organl-zsh-theme
+++ b/init/install-organl-zsh-theme
@@ -9,8 +9,13 @@ if [ ! -d ~/.oh-my-zsh ]; then
 fi
 
 if [ ! -d ~/.oh-my-zsh/custom/.git ]; then
-    { cd ~/.oh-my-zsh && \
-      rm -rf ~/.oh-my-zsh/custom && \
-      git clone git@github.com:organl/oh-my-zsh-organl.git custom } || { echo "Unable to bootstrap oh-my-zsh OrganL theme!" && exit -1}
+  echo "OrganL oh-my-zsh theme is not installed."
+  echo "Cloning OrganL theme (RW) to: ~/.oh-my-zsh/custom"
+  git clone git@github.com:organl/oh-my-zsh-organl.git custom
+  then [ $? -eq 0 ];
+    echo "Clone failed, trying fallback..."
+    echo "Cloning OrganL theme (RO) to: ~/.oh-my-zsh/custom"
+    git clone https://github.com/organl/oh-my-zsh-organl.git custom
+  fi
 fi
 
